In [1]:
import yfinance as yf
import pandas as pd
import numpy as np 
import warnings
warnings.filterwarnings('ignore')

from AA import AssetDataDownloader, AssetAllocation

In [2]:
downloader = AssetDataDownloader()

assets = ["MSFT", "COST", "GOOG", "SYK", "FANG", "ODFL", "AAPL"] 
benchmark = '^GSPC'  
start_date = '2019-01-01'
end_date = '2023-12-31'
rf = .065

asset_prices, benchmark_prices = downloader.download_data(start_date= start_date, end_date= end_date,
                                                          assets= assets, benchmark=benchmark)

Asset_allocator = AssetAllocation(asset_prices = asset_prices,benchmark_prices = benchmark_prices, rf=rf)

[*********************100%%**********************]  7 of 7 completed
[*********************100%%**********************]  1 of 1 completed


In [4]:
Asset_allocator.run_MC_optimizations()

AAPL      COST      FANG      GOOG      MSFT  \
Max Sharpe            0.186386  0.332686  0.054525  0.024008  0.085794   
Max Omega             0.705404  0.011639  0.031356  0.014937  0.106060   
Min VaR (Empirical)   0.086821  0.025140  0.709952  0.026674  0.034988   
Min VaR (Parametric)  0.010203  0.604674  0.021442  0.067597  0.063765   

                          ODFL       SYK  Optimized Value  
Max Sharpe            0.303084  0.013518         0.070705  
Max Omega             0.042122  0.088482         1.141791  
Min VaR (Empirical)   0.066680  0.049745        -0.029587  
Min VaR (Parametric)  0.067045  0.165274        -0.022516

In [3]:
Asset_allocator.run_SLSQP_optimizations()

AAPL      COST      FANG      GOOG      MSFT  \
Max Sharpe            0.301609  0.344388  0.055136  0.010000  0.010000   
Max Omega             0.940000  0.010000  0.010000  0.010000  0.010000   
Min VaR (Empirical)   0.201757  0.010000  0.044387  0.131241  0.304939   
Min VaR (Parametric)  0.010000  0.635983  0.051151  0.064577  0.010000   

                          ODFL       SYK  Optimized Value  
Max Sharpe            0.268867  0.010000         0.071535  
Max Omega             0.010000  0.010000         1.153850  
Min VaR (Empirical)   0.297676  0.010000        -0.025697  
Min VaR (Parametric)  0.024267  0.204022        -0.022357

-----

-------

In [3]:
Asset_allocator = AssetAllocation(asset_prices = asset_prices,benchmark_prices = benchmark_prices, rf=rf)
Asset_allocator.run_optimizations()

Max Sharpe Ratio Weights (%)  Max Omega Ratio Weights (%)  \
AAPL                                   30.160970                     94.00000   
COST                                   34.438792                      1.00000   
FANG                                    5.513552                      1.00000   
GOOG                                    1.000000                      1.00000   
MSFT                                    1.000000                      1.00000   
ODFL                                   26.886686                      1.00000   
SYK                                     1.000000                      1.00000   
Optimization Value                      0.071535                      1.15385   

                    Min VaR empirical Weights (%)  Min VaR cov-var Weights (%)  
AAPL                                    28.155215                     1.000000  
COST                                     1.000000                    63.598334  
FANG                                     2.756791                     5.115139  
GOOG                                    12.773259                     6.457652  
MSFT                                    26.120907                     1.000000  
ODFL                                    28.193828                     2.426661  
SYK                                      1.000000                    20.402214  
Optimization Value                      -7.611330                   -11.465708

--------------

----------

In [4]:
optimized_weights, sharpe = Asset_allocator.optimize_max_sharpe()
optimized_weights, sharpe 

C:\Users\lalos\anaconda3\lib\site-packages\scipy\optimize\optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "


(array([0.30161009, 0.34438724, 0.05513564, 0.01      , 0.01      ,
        0.26886703, 0.01      ]),
 0.07153521402991408)

In [11]:
optimized_weights, omega = Asset_allocator.optimize_for_omega()
optimized_weights, omega 

C:\Users\lalos\anaconda3\lib\site-packages\scipy\optimize\optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "


(array([0.94, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]), 1.1538501949852684)

In [5]:
optimized_weights, minvar = Asset_allocator.minimize_var()
optimized_weights, minvar

(array([0.11521844, 0.10440944, 0.22059248, 0.1       , 0.22474835,
        0.13503129, 0.1       ]),
 -0.02213345518807004)

In [5]:
optimized_weights, minvar = Asset_allocator.minimize_var()
optimized_weights, minvar

(array([0.01      , 0.63598322, 0.05115135, 0.06457652, 0.01      ,
        0.02426611, 0.2040228 ]),
 0.022357496307870397)

In [4]:
optimized_weights, minvar = Asset_allocator.minimize_var()
optimized_weights, minvar

C:\Users\lalos\anaconda3\lib\site-packages\scipy\optimize\optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "


(array([0.01      , 0.63598308, 0.05115124, 0.06457685, 0.01      ,
        0.02426663, 0.2040222 ]),
 7.120703247877434)

In [7]:
asset_prices.iloc[-1].dot(optimized_weights) * -0.02213345518807004

-6.830310625679822

In [4]:
asset_returns = asset_prices.pct_change().dropna()
benchmark_returns = benchmark_prices.pct_change().dropna()
asset_cov_matrix = asset_returns.cov()
rf = .1165

In [5]:
portfolio_rend

NameError: name 'portfolio_rend' is not defined

In [6]:
asset_returns = asset_prices.pct_change().dropna()
asset_cov_matrix = asset_returns.cov()
rf = .1165

average_asset_returns = asset_prices.pct_change().dropna().mean()
start_weights = np.full(len(average_asset_returns), 1/len(average_asset_returns))
portfolio_rend = np.dot(average_asset_returns, start_weights)

variance = np.dot(np.dot(start_weights, asset_cov_matrix), start_weights)
volatility = np.sqrt(variance)

rf = rf/252

Sharpe = (portfolio_rend - rf)/volatility

In [4]:
import numpy as np
import scipy.optimize as sco

asset_returns = asset_prices.pct_change().dropna()
asset_cov_matrix = asset_returns.cov()
average_asset_returns = asset_returns.mean()
start_weights = np.full(len(average_asset_returns), 1 / len(average_asset_returns))

# Tasa libre de riesgo anual, ajustada a diario
rf_daily = rf / 252

# Función para calcular el negativo del ratio de Sharpe
def neg_sharpe_ratio(weights, average_asset_returns, cov_matrix, rf_daily):
    portfolio_return = np.dot(weights, average_asset_returns)
    portfolio_volatility = np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))
    sharpe_ratio = (portfolio_return - rf_daily) / portfolio_volatility
    return -sharpe_ratio  # Negativo porque estamos minimizando

# Restricciones y límites para los pesos
constraints = ({'type': 'eq', 'fun': lambda x: np.sum(x) - 1})  # La suma de los pesos debe ser 1
bounds = tuple((0, 1) for _ in range(len(start_weights)))  # Los pesos deben estar entre 0 y 1

# Optimización
opts = sco.minimize(neg_sharpe_ratio, start_weights, args=(average_asset_returns, asset_cov_matrix, rf_daily),
                    method='SLSQP', bounds=bounds, constraints=constraints)

# Resultados de la optimización
optimized_weights = opts.x
optimized_sharpe = -opts.fun  # Negativo porque minimizamos el negativo del ratio de Sharpe

print("Pesos optimizados:", optimized_weights)
print("Ratio de Sharpe optimizado:", optimized_sharpe)


Pesos optimizados: [3.13442417e-01 3.56327240e-01 5.77706230e-02 4.44793941e-17
 0.00000000e+00 2.72459719e-01 3.52365706e-19]
Ratio de Sharpe optimizado: 0.07192814647143334


In [44]:
Sharpe

0.056991422047103946

In [19]:
from scipy.optimize import minimize

In [48]:
np.dot( start_weights,np.dot(start_weights, asset_cov_matrix))

0.0006458550742122128

In [38]:
volatility

0.02541367887993025

In [37]:
asset_cov_matrix

AAPL      GOOG      MSFT
AAPL  0.000868  0.000537  0.000686
GOOG  0.000537  0.000585  0.000572
MSFT  0.000686  0.000572  0.000769

In [5]:
average_asset_returns

AAPL    0.002769
GOOG    0.001252
MSFT    0.001711
dtype: float64

In [14]:
portfolio_market_gap = asset_returns - benchmark_returns.values
downside = portfolio_market_gap[portfolio_market_gap < 0].fillna(0).std()
upside = portfolio_market_gap[portfolio_market_gap > 0].fillna(0).std()
omega = upside/downside
omega

AAPL    1.365584
GOOG    1.158482
MSFT    1.201645
dtype: float64

In [13]:
portfolio_market_gap

AAPL      GOOG      MSFT
Date                                    
2020-01-03 -0.002662  0.002153 -0.005392
2020-01-06  0.004435  0.021124 -0.000949
2020-01-07 -0.001900  0.002179 -0.006314
2020-01-08  0.011184  0.002978  0.011026
2020-01-09  0.014586  0.004389  0.005838
...              ...       ...       ...
2020-12-23 -0.007722  0.004406 -0.013785
2020-12-24  0.004175  0.000198  0.004291
2020-12-28  0.027043  0.012694  0.001199
2020-12-29 -0.011087 -0.007553 -0.001373
2020-12-30 -0.009868 -0.012259 -0.012361

[251 rows x 3 columns]

In [7]:
df = pd.DataFrame({
    'Valores': range(1, 16)  # Los valores van del 1 al 15
})
df.head(5)

Valores
0        1
1        2
2        3
3        4
4        5

In [7]:
df.quantile(.05)

Valores    1.7
Name: 0.05, dtype: float64

In [8]:
pv = asset_prices.dot(optimized_weights)

NameError: name 'optimized_weights' is not defined

In [15]:
pr = pv.pct_change().dropna()
pr

Date
2019-01-03   -0.031709
2019-01-04    0.032281
2019-01-07    0.005611
2019-01-08    0.013995
2019-01-09    0.006799
                ...   
2023-12-22    0.007071
2023-12-26    0.004431
2023-12-27    0.004315
2023-12-28   -0.004712
2023-12-29   -0.007014
Length: 1257, dtype: float64

In [28]:
pr.quantile(.05) *last_portfolio_value

-8.322153867811833

In [23]:

from scipy.stats import norm
confidence_level= .05
n = norm.ppf(1 - confidence_level) * volatility

In [4]:
n

NameError: name 'n' is not defined

In [26]:
n * last_portfolio_value

10.267170191234507

In [25]:
asset_returns = asset_prices.pct_change().dropna()
asset_cov_matrix = asset_returns.cov()

portfolio_rend = np.dot(asset_prices, optimized_weights)
last_portfolio_value = asset_prices.dot( optimized_weights).iloc[-1]

variance = np.dot(np.dot(optimized_weights, asset_cov_matrix), optimized_weights)
volatility = np.sqrt(variance)
volatility

0.015184132175142655

In [24]:
sum(np.random.dirichlet(alpha=np.ones(4)))

1.0

In [5]:
a, t = Asset_allocator.portfolio_autocorr_penalty(optimized_weights)

In [6]:
a

1.126507659215745

In [7]:
t

0.11865641348339123